### ISSUE TITLE
Ошибка валидатора yii2

### ISSUE THREAD

**Issue by shah-typhoon** [PendalF89/yii2-tinymce#3]
При отправке формы происходит ошибка валидации, поскольку tinymce не записывает содержимое окна редактора в соответствующий textarea и в момент валидации поле пустое.
Предлагаю добавить свойство `public $triggerSaveOnBeforeValidateForm = true;` (или любой другой, название не суть) и добавить в виджет обработчик события формы beforeValidate как у 2amigos [https://github.com/2amigos/yii2-tinymce-widget/blob/master/src/TinyMce.php](https://github.com/2amigos/yii2-tinymce-widget/blob/master/src/TinyMce.php)
Иначе приходится отказываться от Вашего TinyMCE и строить костыли через classMap. Нравится Ваш filemanager :)

**Comment by PendalF89** [comment]
Здравствуйте! Спасибо за найденный баг, сделайте пожалуйста pull request.
